FROM ceccocats/tkdnn:latest
LABEL maintainer "Francesco Gatti"

RUN apt-get update && apt-get install libboost-filesystem-dev libboost-program-options1.65-dev -y
WORKDIR /workspace

# RUN cd && git clone https://github.com/ceccocats/tkDNN.git && cd tkDNN && mkdir build && cd build \ 
    # && cmake .. && make -j12


