#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#include <string>

/**
 * These constants are the lookup strings for the setup .json file generated by python.
 * By making them constant variables it ensures if they ever change the strings only need to be updated here.
 */

const std::string g_classes{"classes"};

#endif